# similar parts of execution
defaults: &defaults
  working_directory: ~/alda-mode
  steps:
    - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    - checkout
    - run: ~/.cask/bin/cask install
    - run: ~/.cask/bin/cask exec ert-runner

version: 2
jobs:
  emacs-25-1:
    <<: *defaults
    docker:
      - image: silex/emacs:25.1

  emacs-24-3:
    <<: *defaults
    docker:
      - image: silex/emacs:24.3

workflows:
  version: 2
  build_and_test:
    jobs:
      - emacs-25-1
      - emacs-24-3
