# similar parts of execution
defaults: &defaults
  working_directory: ~/alda-mode
  steps:
    - run:
        name: Install Cask
        command: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    - checkout
    - run:
        name: Install Cask Deps
        command: ~/.cask/bin/cask install
    - run:
        name: Run Tests
        command: ~/.cask/bin/cask exec ert-runner

version: 2
jobs:
  emacs-25-2:
    <<: *defaults
    docker:
      - image: silex/emacs:25.2
  emacs-25-1:
    <<: *defaults
    docker:
      - image: silex/emacs:25.1
  emacs-24-5:
    <<: *defaults
    docker:
      - image: silex/emacs:24.5

workflows:
  version: 2
  build_and_test:
    jobs:
      - emacs-25-2
      - emacs-25-1
      - emacs-24-5
