version: 2
jobs:
  emacs-25-1:
    docker:
      - image: silex/emacs:25.1
    working_directory: ~/alda-mode
    steps:
      - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - checkout
      - run: ~/.cask/bin/cask install
      - run: ~/.cask/bin/cask exec ert-runner

  emacs-24-3:
    docker:
      - image: silex/emacs:24.3
    working_directory: ~/alda-mode
    steps:
      - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - checkout
      - run: ~/.cask/bin/cask install
      - run: ~/.cask/bin/cask exec ert-runner

workflows:
  version: 2
  build_and_test:
    jobs:
      - emacs-25-1
      - emacs-24-3
